export const staticRouteSeo = {
  "/": {
    title: "Silk Road & Central Asia Tours | Go To Central Asia",
    description: "Plan private, group and tailor-made Silk Road tours across Uzbekistan, Kazakhstan, Kyrgyzstan, Tajikistan, Turkmenistan and the Caucasus with local experts.",
    h1: "Central Asia Tours and Silk Road Travel Packages",
    body: [
      "Go To Central Asia plans private and group tours across Uzbekistan, Kazakhstan, Kyrgyzstan, Tajikistan, Turkmenistan and the Caucasus with licensed guides, reliable hotels, airport transfers and regional travel support.",
      "Compare classic Silk Road city routes, mountain journeys, desert programs, short city tours and multi-country itineraries designed around your dates, pace and comfort level."
    ]
  },
  "/contact": { title: "Contact Go To Central Asia | Travel Specialists", description: "Contact our Tashkent-based Central Asia travel team for custom itineraries, tour prices, visa questions, transfers, hotels and booking support.", h1: "Contact Go To Central Asia", body: ["Send your preferred dates, route ideas and traveler details to receive practical advice from our regional tour specialists.", "We help with private tours, group departures, transfers, hotels, visa guidance and multi-country planning across Central Asia and the Caucasus."] },
  "/about": { title: "About Go To Central Asia | Local Tour Operator Team", description: "Meet Go To Central Asia, a regional tour operator arranging authentic Silk Road journeys with local guides, careful logistics and personal service.", h1: "About Go To Central Asia", body: ["Go To Central Asia is built around local destination knowledge, responsive communication and reliable travel operations in Uzbekistan and neighboring countries.", "Our team designs cultural tours, nature programs, private journeys and group departures with clear inclusions, realistic timing and practical on-trip support."] },
  "/visa-policy": { title: "Central Asia Visa Policy Guide | Entry Requirements", description: "Check practical visa and entry guidance for Uzbekistan, Kazakhstan, Kyrgyzstan, Tajikistan, Turkmenistan and Caucasus tour planning.", h1: "Central Asia Visa Policy Guide", body: ["Visa rules vary by nationality, passport validity and itinerary, so travelers should confirm requirements before booking flights.", "Our team can advise on documentation timing, border crossings and itinerary planning for multi-country Silk Road tours."] },
  "/booking-form": { title: "Book a Central Asia Tour | Request Your Itinerary", description: "Submit your tour booking request with travel dates, destinations, hotel preferences and group size for a tailored Central Asia quotation.", h1: "Book Your Central Asia Tour", body: ["Use the booking form to share your route, preferred pace, rooming details, interests and budget so we can prepare a clear proposal.", "Requests can cover Uzbekistan classics, mountain routes, Silk Road extensions, private tours, group departures, transfers and hotels."] },
  "/transfer": { title: "Central Asia Transfers | Airport & Intercity Transport", description: "Arrange airport pickups, train station transfers and private intercity transport in Uzbekistan and Central Asia with dependable local drivers.", h1: "Central Asia Transfer Services", body: ["Book practical transport support for arrivals, departures, city-to-city moves and border-connected routes.", "Transfers can be combined with guides, sightseeing stops, rail tickets and hotel bookings for a smoother itinerary."] },
  "/hotels": { title: "Central Asia Hotels | Accommodation Booking Support", description: "Browse hotel options for Uzbekistan and Central Asia tours, from boutique Silk Road stays to comfortable city hotels with booking assistance.", h1: "Central Asia Hotels", body: ["Choose accommodation that matches your route, budget and comfort expectations in major Silk Road cities and regional capitals.", "Our hotel support can be integrated with tours, transfers, rail tickets and guided sightseeing."] },
  "/search": { title: "Search Central Asia Tours | Go To Central Asia", description: "Search Go To Central Asia tour packages, destinations, city guides, hotels and travel information for planning your Silk Road trip.", h1: "Search Tours and Travel Pages", body: ["Find relevant tour pages, destination guides and practical travel information across the Go To Central Asia website."] , robots: "noindex,follow" },
  "/10-best-places-to-visit-in-uzbekistan": { title: "10 Best Places to Visit in Uzbekistan | Travel Guide", description: "Discover Uzbekistan's best places to visit, including Samarkand, Bukhara, Khiva, Tashkent, the Ferghana Valley and desert heritage sites.", h1: "10 Best Places to Visit in Uzbekistan", body: ["Use this guide to compare Uzbekistan's essential cities, monuments, markets and regional highlights before building your itinerary.", "The list is helpful for first-time visitors planning a classic Silk Road tour or a longer private journey."] , type: "article" },

  "/uzbek-tours": { title: "Uzbekistan Tours | Group and Private Silk Road Trips", description: "Book Uzbekistan tours featuring Tashkent, Samarkand, Bukhara, Khiva, Ferghana Valley, expert guides, trains, hotels and Silk Road heritage.", h1: "Uzbekistan Tours", body: ["Uzbekistan tours focus on tiled monuments, old bazaars, desert fortresses, craft traditions and the historic trade cities of the Silk Road.", "Choose group departures for fixed dates or private itineraries with flexible hotels, guides and extensions."] },
  "/kazakh-tours": { title: "Kazakhstan Tours | Almaty, Astana and Steppe Routes", description: "Explore Kazakhstan tours with Almaty, Astana, Charyn Canyon, national parks, steppe scenery, modern cities and Central Asia extensions.", h1: "Kazakhstan Tours", body: ["Kazakhstan itineraries combine futuristic capitals, mountain landscapes, canyon walks, nomadic history and wide steppe horizons.", "Programs can connect with Uzbekistan, Kyrgyzstan or Silk Road rail and flight routes."] },
  "/kyrgyz-tours": { title: "Kyrgyzstan Tours | Mountains, Lakes and Nomad Culture", description: "Plan Kyrgyzstan tours to Bishkek, Issyk-Kul, Song-Kul, Karakol, alpine valleys, yurt camps, horse routes and scenic mountain passes.", h1: "Kyrgyzstan Tours", body: ["Kyrgyzstan tours are ideal for travelers seeking mountain scenery, nomad hospitality, lakeside villages and active outdoor experiences.", "Routes can include yurt stays, gentle hikes, horse riding, cultural visits and extensions to Uzbekistan or Kazakhstan."] },
  "/tajik-tours": { title: "Tajikistan Tours | Pamir Highway and Fann Mountains", description: "Discover Tajikistan tours with Dushanbe, the Pamir Highway, Fann Mountains, Seven Lakes, mountain villages and adventurous road journeys.", h1: "Tajikistan Tours", body: ["Tajikistan rewards travelers with dramatic mountain roads, Persian-influenced culture, high passes, lakes and remote village hospitality.", "Our programs support careful routing, experienced drivers and realistic timing for adventurous itineraries."] },
  "/turkmen-tours": { title: "Turkmenistan Tours | Ashgabat, Merv and Darvaza", description: "Arrange Turkmenistan tours to Ashgabat, Merv, Nisa, desert routes and the Darvaza gas crater with visa-aware logistics and local guides.", h1: "Turkmenistan Tours", body: ["Turkmenistan tours combine marble Ashgabat, ancient Merv, desert roads, archaeological sites and the dramatic Darvaza crater.", "Planning focuses on permits, border timing, guides and transport coordination."] },
  "/central-asia-tours": { title: "Central Asia Tours | Multi-Country Silk Road Packages", description: "Compare Central Asia tours combining Uzbekistan, Kazakhstan, Kyrgyzstan, Tajikistan and Turkmenistan with guided logistics and flexible routes.", h1: "Central Asia Tours", body: ["Multi-country Central Asia tours connect Silk Road cities, mountains, deserts, modern capitals and nomadic traditions in one regional journey.", "The best routes balance travel time, border procedures, seasonal conditions and meaningful local experiences."] },
  "/silk-road-tours": { title: "Silk Road Tours | Uzbekistan and Central Asia Packages", description: "Book Silk Road tours through Samarkand, Bukhara, Khiva, Tashkent and wider Central Asia with cultural guides and private or group options.", h1: "Silk Road Tours", body: ["Silk Road tours follow caravan history through monumental cities, markets, mausoleums, madrasahs and living craft traditions.", "Routes can stay within Uzbekistan or extend across Central Asia and the Caucasus."] },
  "/caucasus-tours": { title: "Caucasus Tours | Georgia, Armenia and Azerbaijan", description: "Plan Caucasus tours covering Georgia, Armenia and Azerbaijan with Tbilisi, Yerevan, Baku, mountain scenery, wine routes and heritage sites.", h1: "Caucasus Tours", body: ["Caucasus tours add churches, wine valleys, mountain roads, Caspian architecture and distinctive cuisine to a regional itinerary.", "They work well as standalone journeys or extensions after Central Asia tours."] },
  "/armenia-tours": { title: "Armenia Tours | Yerevan, Monasteries and Landscapes", description: "Explore Armenia tours with Yerevan, ancient monasteries, Lake Sevan, mountain viewpoints, local cuisine and private Caucasus itineraries.", h1: "Armenia Tours", body: ["Armenia offers monastery routes, stone architecture, highland views, warm hospitality and layered cultural history.", "Private programs can connect Yerevan with Georgia and Azerbaijan for a broader Caucasus journey."] },
  "/azerbaijan-tours": { title: "Azerbaijan Tours | Baku, Gobustan and the Caucasus", description: "Book Azerbaijan tours featuring Baku, Gobustan, mud volcanoes, Absheron, Caspian scenery, old city walks and Caucasus extensions.", h1: "Azerbaijan Tours", body: ["Azerbaijan blends Baku's modern skyline with medieval lanes, fire temples, rock art and diverse landscapes.", "Trips can be tailored as short city breaks or part of a Georgia-Armenia-Azerbaijan route."] },
  "/georgia-tours": { title: "Georgia Tours | Tbilisi, Wine Regions and Mountains", description: "Discover Georgia tours with Tbilisi, Kakheti wine country, Kazbegi mountains, cave towns, monasteries, cuisine and Caucasus culture.", h1: "Georgia Tours", body: ["Georgia tours combine lively cities, mountain passes, wine traditions, monasteries, cave towns and memorable food experiences.", "Itineraries can be relaxed cultural journeys or active programs with scenic drives and village stays."] }
};

const destinationPages = {
  "/uzbekistan": ["Uzbekistan Travel Guide | Samarkand, Bukhara and Khiva", "Plan Uzbekistan travel with Silk Road cities, fast trains, bazaars, monuments, hotels, guides and route ideas for Samarkand, Bukhara, Khiva and Tashkent.", "Uzbekistan Travel Guide"],
  "/kazakhstan": ["Kazakhstan Travel Guide | Almaty, Astana and Nature", "Plan Kazakhstan travel with Almaty, Astana, canyons, lakes, national parks, steppe landscapes and multi-country Central Asia route ideas.", "Kazakhstan Travel Guide"],
  "/kyrgyzstan": ["Kyrgyzstan Travel Guide | Lakes, Yurts and Mountains", "Plan Kyrgyzstan travel around Bishkek, Issyk-Kul, Song-Kul, Karakol, yurt camps, horse riding, alpine valleys and nomad culture.", "Kyrgyzstan Travel Guide"],
  "/tajikistan": ["Tajikistan Travel Guide | Pamirs and Fann Mountains", "Plan Tajikistan travel with Dushanbe, Pamir Highway routes, Fann Mountains, Seven Lakes, high passes and village-based cultural experiences.", "Tajikistan Travel Guide"],
  "/turkmenistan": ["Turkmenistan Travel Guide | Ashgabat, Merv and Darvaza", "Plan Turkmenistan travel with Ashgabat, Merv, Nisa, desert routes, Darvaza gas crater, permits, guides and Silk Road logistics.", "Turkmenistan Travel Guide"],
  "/central-asia": ["Central Asia Travel Guide | Multi-Country Route Ideas", "Plan Central Asia travel across Uzbekistan, Kazakhstan, Kyrgyzstan, Tajikistan and Turkmenistan with route advice, seasons and logistics.", "Central Asia Travel Guide"],
  "/silk-road": ["Silk Road Travel Guide | Historic Routes and Cities", "Explore Silk Road travel ideas linking Samarkand, Bukhara, Khiva, Tashkent, mountains, deserts and caravan heritage across Central Asia.", "Silk Road Travel Guide"],
  "/caucasus": ["Caucasus Travel Guide | Georgia, Armenia and Azerbaijan", "Plan Caucasus travel through Georgia, Armenia and Azerbaijan with Tbilisi, Yerevan, Baku, mountains, monasteries, wine and Caspian culture.", "Caucasus Travel Guide"],
  "/armenia": ["Armenia Travel Guide | Yerevan and Ancient Monasteries", "Plan Armenia travel with Yerevan, Lake Sevan, Garni, Geghard, ancient monasteries, mountain views, cuisine and Caucasus extensions.", "Armenia Travel Guide"],
  "/azerbaijan": ["Azerbaijan Travel Guide | Baku and Caspian Highlights", "Plan Azerbaijan travel with Baku Old City, Flame Towers, Gobustan, Absheron, mud volcanoes, Caspian views and Caucasus extensions.", "Azerbaijan Travel Guide"],
  "/georgia": ["Georgia Travel Guide | Tbilisi, Wine and Mountains", "Plan Georgia travel with Tbilisi, Kakheti wine region, Kazbegi, Mtskheta, cave towns, monasteries, mountain landscapes and cuisine.", "Georgia Travel Guide"]
};
for (const [path, [title, description, h1]] of Object.entries(destinationPages)) {
  staticRouteSeo[path] = { title, description, h1, body: [`${h1} introduces the main sights, travel seasons, route options and practical considerations for building a rewarding itinerary.`, "Use this page to compare cultural highlights, transport needs, recommended pacing and ways to combine the destination with nearby countries."] };
}

const cityPages = {
  "/uzbekistan-tashkent": ["Tashkent Travel Guide | Uzbekistan Capital City", "Discover Tashkent with Chorsu Bazaar, Khast Imam, metro stations, museums, parks, restaurants and easy connections to Samarkand and Bukhara."],
  "/uzbekistan-samarkand": ["Samarkand Travel Guide | Registan and Timurid Heritage", "Explore Samarkand highlights including Registan Square, Shah-i-Zinda, Gur-e-Amir, Bibi-Khanym, Siyob Bazaar and Timurid architecture."],
  "/uzbekistan-bukhara": ["Bukhara Travel Guide | Old City and Silk Road Monuments", "Plan a Bukhara visit with Poi Kalyan, Lyabi Hauz, Ark Fortress, trading domes, madrasahs, craft workshops and atmospheric old streets."],
  "/uzbekistan-khiva": ["Khiva Travel Guide | Itchan Kala Walled City", "Visit Khiva's Itchan Kala with Kalta Minor, Juma Mosque, Tosh Hovli Palace, minarets, museums and desert Silk Road atmosphere."],
  "/rus/uzbekistan-tashkent": ["Путеводитель по Ташкенту | Столица Узбекистана", "Откройте Ташкент: базар Чорсу, комплекс Хаст-Имам, станции метро, музеи, парки, рестораны и удобные маршруты в Самарканд и Бухару.", "Ташкент, Узбекистан"],
  "/rus/uzbekistan-samarkand": ["Путеводитель по Самарканду | Регистан и наследие Тимуридов", "Изучите главные достопримечательности Самарканда: площадь Регистан, Шахи-Зинда, Гур-Эмир, Биби-Ханым, Сиабский базар и архитектуру эпохи Тимуридов.", "Самарканд, Узбекистан"],
  "/rus/uzbekistan-bukhara": ["Путеводитель по Бухаре | Старый город и памятники Шёлкового пути", "Планируйте поездку в Бухару с комплексом Пои-Калян, Ляби-Хауз, крепостью Арк, торговыми куполами, медресе, ремесленными мастерскими и атмосферными старыми улицами.", "Бухара, Узбекистан"],
  "/rus/uzbekistan-khiva": ["Путеводитель по Хиве | Крепостной город Ичан-Кала", "Посетите хивинскую Ичан-Калу с Кальта-Минором, Джума-мечетью, дворцом Таш-Хаули, минаретами, музеями и пустынной атмосферой Шёлкового пути.", "Хива, Узбекистан"],
  "/kazakhstan-astana": ["Astana Travel Guide | Kazakhstan Capital Highlights", "Explore Astana with modern architecture, museums, riverfront walks, cultural landmarks and Kazakhstan tour connections."],
  "/kazakhstan-almaty": ["Almaty Travel Guide | Mountains, Parks and City Life", "Plan Almaty travel with mountain viewpoints, Green Bazaar, Kok-Tobe, parks, museums, restaurants and day trips to canyons and lakes."],
  "/kyrgyzstan-bishkek": ["Bishkek Travel Guide | Kyrgyzstan Capital and Ala-Archa", "Discover Bishkek with Ala-Too Square, Osh Bazaar, parks, museums, cafes and day trips to Ala-Archa National Park."],
  "/kyrgyzstan-osh": ["Osh Travel Guide | Sulaiman-Too and Silk Road Bazaar", "Explore Osh with Sulaiman-Too, lively markets, Uzbek-Kyrgyz culture, mountain gateways and southern Kyrgyzstan route ideas."],
  "/tajikistan-dushanbe": ["Dushanbe Travel Guide | Tajikistan Capital Highlights", "Plan Dushanbe sightseeing with museums, parks, bazaars, monuments, teahouses and starting points for Pamir and Fann Mountain journeys."],
  "/turkmenistan-ashgabat": ["Ashgabat Travel Guide | Turkmenistan Capital", "Visit Ashgabat for marble avenues, monuments, museums, bazaars, nearby Nisa and connections to Merv, Darvaza and desert routes."],
  "/azerbaijan-baku": ["Baku Travel Guide | Old City, Caspian and Gobustan", "Explore Baku with Icherisheher, Flame Towers, Boulevard, museums, Absheron fire sites, Gobustan rock art and Caspian views."],
  "/caucasus-baku": ["Caucasus Baku Guide | Azerbaijan Capital Extension", "Add Baku to a Caucasus itinerary with Old City walks, Caspian architecture, Gobustan, Absheron and regional flight connections."],
  "/armenia-yerevan": ["Yerevan Travel Guide | Armenia Capital and Day Trips", "Discover Yerevan with Republic Square, Cascade, museums, cafes, markets and day trips to Garni, Geghard and Lake Sevan."],
  "/caucasus-yerevan": ["Caucasus Yerevan Guide | Armenia Tour Extension", "Plan Yerevan as part of a Caucasus route with city walks, monastery day trips, cuisine, museums and Georgia-Armenia connections."],
  "/georgia-tbilisi": ["Tbilisi Travel Guide | Old Town, Cuisine and Wine", "Explore Tbilisi with sulfur baths, Narikala Fortress, old streets, wine bars, museums, cuisine and day trips around Georgia."],
  "/caucasus-tbilisi": ["Caucasus Tbilisi Guide | Georgia Gateway City", "Use Tbilisi as a Caucasus gateway for old town walks, wine country, mountain routes, Georgia-Armenia-Azerbaijan itineraries and regional culture."]
};
for (const [path, [title, description]] of Object.entries(cityPages)) {
  const h1 = title.split(" | ")[0];
  staticRouteSeo[path] = { title, description, h1, body: [`${h1} helps travelers understand the city's main sights, neighborhoods, local experiences and best ways to include it in a wider tour.`, "Our team can arrange guides, transfers, hotels and day trips so the visit fits smoothly into a private or group itinerary."] };
}

const tourStylePages = {
  "/city-tours": ["Central Asia City Tours | Tashkent, Samarkand and More", "Book short city tours in Tashkent, Samarkand, Bukhara, Khiva, Almaty, Bishkek, Dushanbe, Ashgabat, Baku, Tbilisi and Yerevan."],
  "/cultural-tours": ["Central Asia Cultural Tours | Silk Road Heritage", "Explore Central Asia cultural tours with monuments, museums, bazaars, craft workshops, local food, historical guides and Silk Road cities."],
  "/gastronomy-tours": ["Central Asia Gastronomy Tours | Food and Bazaar Trips", "Taste Central Asia through gastronomy tours featuring plov, bread, tea houses, markets, cooking classes, wine, sweets and regional specialties."],
  "/religious-tours": ["Central Asia Religious Tours | Sacred Heritage Routes", "Plan religious and pilgrimage tours to mausoleums, mosques, madrasahs, churches, monasteries and sacred heritage sites across Central Asia."],
  "/eco-tours": ["Central Asia Eco Tours | Mountains, Lakes and Deserts", "Choose eco tours in Central Asia with alpine lakes, canyons, deserts, valleys, national parks, yurt camps and nature-focused itineraries."],
  "/business-mice-tours": ["Central Asia Business and MICE Tours | Corporate Travel", "Arrange business travel, MICE programs, delegation logistics, conference support, incentives, transfers and hotels across Central Asia."]
};
for (const [path, [title, description]] of Object.entries(tourStylePages)) {
  const h1 = title.split(" | ")[0];
  staticRouteSeo[path] = { title, description, h1, body: [`${h1} can be arranged as standalone programs or combined with wider private and group itineraries.`, "We adapt guides, transport, timing, venues and special interests to the needs of each traveler or organization."] };
}

const privateListPages = {
  "/uzbekistan-private-tours": ["Uzbekistan Private Tours | Tailor-Made Silk Road Trips", "Design Uzbekistan private tours with flexible dates, guides, hotels, trains and custom routes through Tashkent, Samarkand, Bukhara and Khiva."],
  "/kazakhstan-private-tours": ["Kazakhstan Private Tours | Custom Almaty and Astana Trips", "Plan Kazakhstan private tours with Almaty, Astana, canyons, national parks, steppe routes, private drivers and flexible extensions."],
  "/kyrgyzstan-private-tours": ["Kyrgyzstan Private Tours | Custom Mountain Itineraries", "Create Kyrgyzstan private tours with Bishkek, Issyk-Kul, Song-Kul, Karakol, yurt stays, horse riding and scenic mountain drives."],
  "/tajikistan-private-tours": ["Tajikistan Private Tours | Pamir and Fann Mountain Routes", "Build Tajikistan private tours with Dushanbe, Pamir Highway, Fann Mountains, Seven Lakes, experienced drivers and tailored adventure pacing."],
  "/turkmenistan-private-tours": ["Turkmenistan Private Tours | Ashgabat, Merv and Darvaza", "Arrange Turkmenistan private tours with Ashgabat, Merv, Nisa, Darvaza gas crater, desert logistics, local guides and permit-aware planning."],
  "/central-asia-private-tours": ["Central Asia Private Tours | Tailor-Made Multi-Country Trips", "Design Central Asia private tours across Uzbekistan, Kazakhstan, Kyrgyzstan, Tajikistan and Turkmenistan with custom dates and logistics."],
  "/silk-road-private-tours": ["Silk Road Private Tours | Custom Heritage Journeys", "Plan Silk Road private tours through Uzbekistan and Central Asia with flexible routes, local guides, handpicked hotels and cultural experiences."],
  "/caucasus-private-tours": ["Caucasus Private Tours | Georgia, Armenia and Azerbaijan", "Create Caucasus private tours with Tbilisi, Yerevan, Baku, wine regions, monasteries, mountains and tailored cross-border logistics."],
  "/armenia-private-tours": ["Armenia Private Tours | Custom Yerevan and Monastery Trips", "Plan Armenia private tours with Yerevan, Lake Sevan, Garni, Geghard, monasteries, mountain viewpoints, cuisine and flexible guides."],
  "/azerbaijan-private-tours": ["Azerbaijan Private Tours | Custom Baku and Gobustan Trips", "Arrange Azerbaijan private tours with Baku, Gobustan, Absheron, Caspian sights, mountain villages, private guides and Caucasus extensions."],
  "/georgia-private-tours": ["Georgia Private Tours | Custom Tbilisi, Wine and Mountain Trips", "Design Georgia private tours with Tbilisi, Kakheti, Kazbegi, cave towns, monasteries, food, wine and private driver-guide support."]
};
for (const [path, [title, description]] of Object.entries(privateListPages)) {
  const h1 = title.split(" | ")[0];
  staticRouteSeo[path] = { title, description, h1, body: [`${h1} give travelers control over departure dates, hotels, pacing, guides and special interests.`, "Tell us your priorities and we will shape transport, sightseeing, meals, extensions and rest time into one practical itinerary."] };
}


const additionalTourDetailPages = {
  "/tour/1-day-chimgan-and-charvak-tour": ["1-Day Chimgan and Charvak Tour | Tashkent Mountain Escape", "Take a one-day Chimgan and Charvak tour from Tashkent with mountain views, lake scenery, cable car options, local lunch stops and private transfers.", "1-Day Chimgan and Charvak Tour", ["Escape Tashkent for a day in the Western Tien Shan foothills, where Chimgan mountains and Charvak reservoir offer fresh air, panoramas and an easy nature break.", "This short private tour works well before or after a Silk Road itinerary and can include hotel pickup, scenic stops, optional cable car time, lunch arrangements and a flexible return to the city."]],
  "/tour/6-day-private-classic-uzbekistan-tour": ["6-Day Private Classic Uzbekistan Tour | Tashkent to Bukhara", "Plan a 6-day private Uzbekistan tour linking Tashkent, Samarkand and Bukhara with guides, train logistics, hotels and Silk Road sightseeing.", "6-Day Private Classic Uzbekistan Tour", ["This compact private route focuses on Uzbekistan's most accessible Silk Road highlights while keeping logistics efficient for travelers with limited time.", "Expect guided sightseeing in Tashkent, monument-rich days in Samarkand and atmospheric old-city exploration in Bukhara, with optional extensions to Khiva or the Ferghana Valley."]],
  "/tour/1-day-samarkand-city-tour": ["1-Day Samarkand City Tour | Registan and Timurid Heritage", "Book a one-day Samarkand city tour covering Registan, Shah-i-Zinda, Gur-e-Amir, Bibi-Khanym, Siyob Bazaar and Timurid landmarks with a local guide.", "1-Day Samarkand City Tour", ["A full-day Samarkand tour is the fastest way to understand the city's Timurid architecture, blue-tiled mausoleums, market life and Silk Road legacy.", "The program can be arranged for travelers staying in Samarkand or arriving by train from Tashkent or Bukhara, with timing adapted to rail schedules."]],
  "/tour/1-day-tashkent-city-tour": ["1-Day Tashkent City Tour | Old City, Bazaar and Metro", "Explore Tashkent in one day with Khast Imam, Chorsu Bazaar, Independence Square, decorative metro stations, museums and local food stops.", "1-Day Tashkent City Tour", ["Tashkent blends old mahallas, Islamic heritage, broad Soviet-era avenues, creative restaurants and one of Central Asia's most memorable metro systems.", "This guided city tour is useful for arrival days, stopovers and travelers who want cultural context before continuing to Samarkand, Bukhara or the mountains."]],
  "/tour/10-day-private-classic-uzbekistan-tour": ["10-Day Private Classic Uzbekistan Tour | Relaxed Silk Road Route", "Enjoy a 10-day private Uzbekistan tour with Tashkent, Samarkand, Bukhara, Khiva, deeper sightseeing, flexible hotels and guided Silk Road experiences.", "10-Day Private Classic Uzbekistan Tour", ["The 10-day private classic route gives travelers more breathing room in Uzbekistan's landmark cities, making it ideal for photography, museums, craft visits and unhurried evenings.", "Hotels, guides, train tickets, airport transfers and optional cultural experiences can be tailored to match your pace, interests and preferred comfort level."]],
  "/tour/8-day-private-uzbekistan-tour": ["8-Day Private Uzbekistan Tour | Samarkand, Bukhara and Khiva", "Book an 8-day private Uzbekistan tour through Tashkent, Samarkand, Bukhara and Khiva with flexible dates, local guides and arranged transport.", "8-Day Private Uzbekistan Tour", ["This private Uzbekistan journey connects the country's essential Silk Road cities in a balanced route suitable for couples, families and small groups.", "The itinerary can include train travel, private transfers, licensed guides, entrance arrangements, boutique hotels and extensions to Central Asia neighbors."]],
  "/tour/2-day-seven-holy-scholars-tour": ["2-Day Seven Holy Scholars Tour | Bukhara Pilgrimage Route", "Visit the Seven Holy Scholars near Bukhara on a 2-day spiritual heritage tour with sacred sites, local guidance and comfortable ground logistics.", "2-Day Seven Holy Scholars Tour", ["The Seven Holy Scholars route focuses on important Naqshbandi heritage sites around Bukhara and offers a meaningful addition to a cultural Uzbekistan tour.", "A local guide helps explain the history, etiquette and spiritual context of each stop while drivers manage the countryside routing between shrines."]],
  "/tour/5-day-tashkent-samarkand-tour": ["5-Day Tashkent and Samarkand Tour | Uzbekistan Short Break", "Plan a 5-day Tashkent and Samarkand tour with capital city sightseeing, Registan Square, Shah-i-Zinda, local markets, trains and private guides.", "5-Day Tashkent and Samarkand Tour", ["This short Uzbekistan tour is built for travelers who want a focused introduction to the capital and the country's most famous Silk Road city.", "It can be arranged as a private city-and-rail package with airport transfers, hotels, guided sightseeing and optional food or craft experiences."]],
  "/tour/5-day-tashkent-bukhara-tour": ["5-Day Tashkent and Bukhara Tour | Old City Heritage Trip", "Discover Tashkent and Bukhara in five days with Chorsu Bazaar, Khast Imam, Poi Kalyan, Lyabi Hauz, Ark Fortress and private tour logistics.", "5-Day Tashkent and Bukhara Tour", ["Tashkent and Bukhara create a strong contrast between modern capital energy and one of Central Asia's most atmospheric old cities.", "This tour suits travelers interested in architecture, bazaars, trading domes, religious heritage and slower evenings around historic squares."]],
  "/tour/5-day-tashkent-ferghana-valley-tour": ["5-Day Tashkent and Ferghana Valley Tour | Crafts and Silk", "Travel from Tashkent to the Ferghana Valley for silk workshops, ceramics, markets, Kokand heritage, Rishtan artisans and Margilan traditions.", "5-Day Tashkent and Ferghana Valley Tour", ["The Ferghana Valley is a rewarding choice for travelers who want living craft traditions, fertile landscapes and a different view of Uzbekistan beyond the classic monument route.", "Private planning can include Kokand palace sites, Rishtan ceramics, Margilan silk, local markets and careful transport over or around the mountain pass."]],
  "/tour/4-day-tashkent-samarkand-tour": ["4-Day Tashkent and Samarkand Tour | Fast Uzbekistan Highlights", "See Tashkent and Samarkand in four days with airport transfers, high-speed train planning, city sightseeing and Registan-focused guided touring.", "4-Day Tashkent and Samarkand Tour", ["This efficient program is designed for short stays, business add-ons or travelers who want Uzbekistan's headline experiences with minimal travel complexity.", "The route can be customized around arrival times, train schedules, hotel category and preferred depth of sightseeing in Samarkand."]],
  "/tour/4-day-tashkent-mountains-tour": ["4-Day Tashkent Mountains Tour | Chimgan, Charvak and City", "Combine Tashkent sightseeing with Chimgan and Charvak mountain scenery on a 4-day Uzbekistan nature-and-city tour with private transfers.", "4-Day Tashkent Mountains Tour", ["This route pairs capital city culture with an easy mountain escape, making it suitable for families and travelers who want lighter walking and scenic landscapes.", "Depending on season, the program can include reservoirs, viewpoints, cable car options, local restaurants and relaxed time away from urban traffic."]],
  "/tour/4-day-tashkent-bukhara-tour": ["4-Day Tashkent and Bukhara Tour | Compact Silk Road Escape", "Book a compact 4-day Tashkent and Bukhara tour with airport support, train or flight logistics, old-city sightseeing and private guides.", "4-Day Tashkent and Bukhara Tour", ["A four-day Tashkent and Bukhara itinerary is a practical solution for travelers who want old Silk Road atmosphere in a short window.", "The program can prioritize Poi Kalyan, Lyabi Hauz, trading domes, Ark Fortress, Chorsu Bazaar and comfortable transfers between arrival points."]],
  "/tour/6-day-gastronomy-uzbekistan-tour": ["6-Day Uzbekistan Gastronomy Tour | Plov, Markets and Cooking", "Taste Uzbekistan on a 6-day gastronomy tour with plov, bread, bazaars, cooking classes, tea houses, regional dishes and Silk Road sightseeing.", "6-Day Uzbekistan Gastronomy Tour", ["Uzbek cuisine is closely tied to family rituals, markets, farming regions and Silk Road exchange, making food one of the best ways to understand the country.", "This gastronomy route can combine classic sightseeing with plov centers, bread ovens, bazaar tastings, home-style meals and optional cooking demonstrations."]],
  "/tour/1-day-bukhara-city-tour": ["1-Day Bukhara City Tour | Poi Kalyan, Ark and Old Bazaar", "Explore Bukhara in one day with Poi Kalyan, Lyabi Hauz, Ark Fortress, trading domes, madrasahs, mosques, craft workshops and a local guide.", "1-Day Bukhara City Tour", ["Bukhara's compact old city rewards a guided walking tour because many monuments, domes, courtyards and craft shops sit close together but carry deep historical context.", "This one-day program can be adjusted for hotel pickup, train arrival, photography priorities, museum time and evening atmosphere around Lyabi Hauz."]]
};
for (const [path, [title, description, h1, body]] of Object.entries(additionalTourDetailPages)) {
  staticRouteSeo[path] = { title, description, h1, body, type: "article" };
}

const hotelDetailPages = {
  "/hotels/airport-hotel-24": ["Airport Hotel 24 Tashkent | Rooms and Booking Info", "View Airport Hotel 24 in Tashkent for airport-area stays, room information, transfer convenience, booking support and Uzbekistan arrival planning.", "Airport Hotel 24 Tashkent"],
  "/hotels/corner-hotel": ["Corner Hotel Tashkent | Central Stay for Uzbekistan Tours", "Check Corner Hotel Tashkent details for comfortable city accommodation, tour starts, airport transfers, room options and booking assistance.", "Corner Hotel Tashkent"],
  "/hotels/human-hotel": ["Human Hotel Tashkent | Accommodation for Silk Road Trips", "Review Human Hotel Tashkent for Uzbekistan tour accommodation, room details, location notes, booking support and pre-tour or post-tour stays.", "Human Hotel Tashkent"]
};
for (const [path, [title, description, h1]] of Object.entries(hotelDetailPages)) {
  staticRouteSeo[path] = { title, description, h1, body: [`${h1} can be included before, during or after a wider Uzbekistan and Central Asia itinerary.`, "Use the hotel page to review practical stay details and request booking help together with transfers, guides or tour arrangements."], type: "article" };
}


const attractionSeoPages = {
  "/attractions/registan-square": ["Registan Square Samarkand | Uzbekistan Attraction Guide", "Learn about Registan Square in Samarkand, its three madrasahs, Timurid tilework, photography timing and how to include it in Uzbekistan tours.", "Registan Square Samarkand"],
  "/attractions/shah-i-zinda": ["Shah-i-Zinda Samarkand | Mausoleum Avenue Guide", "Explore Shah-i-Zinda in Samarkand with its blue-tiled mausoleums, sacred heritage, visiting tips and Uzbekistan Silk Road tour context.", "Shah-i-Zinda Samarkand"],
  "/attractions/gur-e-amir": ["Gur-e-Amir Mausoleum | Amir Timur Tomb in Samarkand", "Visit Gur-e-Amir Mausoleum in Samarkand, the resting place of Amir Timur, with history, architecture notes and guided tour planning tips.", "Gur-e-Amir Mausoleum"],
  "/attractions/poi-kalyan": ["Poi Kalyan Bukhara | Minaret, Mosque and Madrasa Guide", "Discover Bukhara's Poi Kalyan ensemble with the Kalyan Minaret, mosque, Mir-i-Arab Madrasa, old city atmosphere and tour planning advice.", "Poi Kalyan Bukhara"],
  "/attractions/itchan-kala": ["Itchan Kala Khiva | Walled City Travel Guide", "Explore Itchan Kala in Khiva with minarets, palaces, museums, city walls, sunset viewpoints and Uzbekistan tour itinerary ideas.", "Itchan Kala Khiva"],
  "/attractions/chorsu-bazaar": ["Chorsu Bazaar Tashkent | Market and Food Guide", "Visit Chorsu Bazaar in Tashkent for produce, bread, spices, sweets, local food, old city culture and guided Uzbekistan city tour planning.", "Chorsu Bazaar Tashkent"],
  "/attractions/ala-archa-national-park": ["Ala-Archa National Park | Bishkek Mountain Day Trip", "Plan an Ala-Archa National Park visit from Bishkek with mountain scenery, walking routes, picnic stops and Kyrgyzstan tour logistics.", "Ala-Archa National Park"],
  "/attractions/song-kul-lake": ["Song-Kul Lake Kyrgyzstan | Yurt Camp and Nomad Guide", "Explore Song-Kul Lake in Kyrgyzstan with yurt camps, summer pastures, horse riding, nomad culture and mountain route planning tips.", "Song-Kul Lake Kyrgyzstan"]
};
for (const [path, [title, description, h1]] of Object.entries(attractionSeoPages)) {
  staticRouteSeo[path] = { title, description, h1, body: [`${h1} is one of the memorable stops travelers can add to a private or group itinerary with Go To Central Asia.`, "The attraction page gives context for sightseeing priorities, guide explanations, timing, nearby stops and how the site fits into a wider regional route."], type: "article" };
}


const privateTourDetailSeoPages = {
  "/private-tour/uzbekistan-classic-silk-road": ["Uzbekistan Classic Silk Road Private Tour | Custom Route", "Customize a private Uzbekistan Classic Silk Road tour with Tashkent, Samarkand, Bukhara, Khiva, train planning, guides and handpicked hotels.", "Uzbekistan Classic Silk Road Private Tour"],
  "/private-tour/uzbekistan-family-tour": ["Uzbekistan Family Private Tour | Kid-Friendly Silk Road Travel", "Plan an Uzbekistan family private tour with child-friendly pacing, comfortable transfers, engaging guides, bazaars, monuments and flexible hotels.", "Uzbekistan Family Private Tour"],
  "/private-tour/uzbekistan-luxury-tour": ["Uzbekistan Luxury Private Tour | Premium Silk Road Itinerary", "Design a luxury Uzbekistan private tour with premium hotels, expert guides, VIP transfers, refined dining and flexible Silk Road sightseeing.", "Uzbekistan Luxury Private Tour"],
  "/private-tour/uzbekistan-photography-tour": ["Uzbekistan Photography Private Tour | Golden Hour Silk Road", "Build a private Uzbekistan photography tour around Registan, Khiva walls, Bukhara lanes, bazaars, early starts and golden-hour viewpoints.", "Uzbekistan Photography Private Tour"],
  "/private-tour/ferghana-valley-private-tour": ["Ferghana Valley Private Tour | Silk, Ceramics and Markets", "Explore the Ferghana Valley on a private tour with Kokand, Rishtan ceramics, Margilan silk, local markets, craftspeople and scenic road travel.", "Ferghana Valley Private Tour"],
  "/private-tour/kyrgyzstan-nomad-culture-tour": ["Kyrgyzstan Nomad Culture Private Tour | Yurts and Horses", "Create a Kyrgyzstan nomad culture private tour with yurt camps, horse riding, Song-Kul, Issyk-Kul, village visits and mountain hospitality.", "Kyrgyzstan Nomad Culture Private Tour"],
  "/private-tour/kyrgyzstan-adventure-tour": ["Kyrgyzstan Adventure Private Tour | Lakes, Canyons and Trails", "Plan a Kyrgyzstan adventure private tour with alpine lakes, canyons, Karakol trails, scenic passes, yurt nights and flexible activity levels.", "Kyrgyzstan Adventure Private Tour"],
  "/private-tour/kazakhstan-nature-tour": ["Kazakhstan Nature Private Tour | Canyons, Lakes and Mountains", "Customize a Kazakhstan nature private tour with Charyn Canyon, Kolsai Lakes, Kaindy Lake, Altyn-Emel, Almaty and private drivers.", "Kazakhstan Nature Private Tour"],
  "/private-tour/kazakhstan-city-and-steppe-tour": ["Kazakhstan City and Steppe Private Tour | Almaty to Astana", "Design a Kazakhstan city and steppe private tour linking Almaty, Astana, museums, modern architecture, landscapes and regional flight logistics.", "Kazakhstan City and Steppe Private Tour"],
  "/private-tour/tajikistan-pamir-highway-tour": ["Tajikistan Pamir Highway Private Tour | High Mountain Road Trip", "Plan a Tajikistan Pamir Highway private tour with experienced drivers, high passes, Wakhan Valley options, village stays and safe pacing.", "Tajikistan Pamir Highway Private Tour"],
  "/private-tour/tajikistan-fann-mountains-tour": ["Tajikistan Fann Mountains Private Tour | Lakes and Villages", "Explore the Fann Mountains on a private Tajikistan tour with Seven Lakes, Iskanderkul, mountain villages, Dushanbe and scenic road support.", "Tajikistan Fann Mountains Private Tour"],
  "/private-tour/turkmenistan-darvaza-tour": ["Turkmenistan Darvaza Private Tour | Desert Crater Journey", "Arrange a Turkmenistan Darvaza private tour with Ashgabat, Karakum Desert logistics, crater viewing, camping options and local guide support.", "Turkmenistan Darvaza Private Tour"],
  "/private-tour/turkmenistan-unesco-tour": ["Turkmenistan UNESCO Private Tour | Merv, Nisa and Ancient Routes", "Plan a Turkmenistan UNESCO private tour with Merv, Nisa, Ashgabat museums, desert roads, permit-aware timing and expert local guiding.", "Turkmenistan UNESCO Private Tour"],
  "/private-tour/central-asia-five-stans-tour": ["Central Asia Five Stans Private Tour | Complete Regional Journey", "Design a Five Stans private tour across Uzbekistan, Kazakhstan, Kyrgyzstan, Tajikistan and Turkmenistan with one coordinated itinerary.", "Central Asia Five Stans Private Tour"],
  "/private-tour/central-asia-two-week-tour": ["Central Asia Two-Week Private Tour | Balanced Multi-Country Route", "Build a two-week Central Asia private tour balancing Silk Road cities, mountains, deserts, border logistics, flights and comfortable pacing.", "Central Asia Two-Week Private Tour"],
  "/private-tour/silk-road-uzbekistan-kyrgyzstan-tour": ["Uzbekistan and Kyrgyzstan Private Tour | Silk Road and Mountains", "Combine Uzbekistan and Kyrgyzstan on a private tour with Samarkand, Bukhara, Tashkent, Bishkek, Issyk-Kul, yurt stays and mountain scenery.", "Uzbekistan and Kyrgyzstan Private Tour"],
  "/private-tour/silk-road-uzbekistan-kazakhstan-tour": ["Uzbekistan and Kazakhstan Private Tour | Cities, Steppe and Canyons", "Plan an Uzbekistan and Kazakhstan private tour with Silk Road monuments, Almaty, Astana, Charyn Canyon, train or flight logistics and guides.", "Uzbekistan and Kazakhstan Private Tour"],
  "/private-tour/caucasus-three-country-tour": ["Caucasus Three-Country Private Tour | Georgia, Armenia and Azerbaijan", "Create a private Caucasus tour through Georgia, Armenia and Azerbaijan with Tbilisi, Yerevan, Baku, wine regions, monasteries and mountains.", "Caucasus Three-Country Private Tour"],
  "/private-tour/georgia-wine-and-mountains-tour": ["Georgia Wine and Mountains Private Tour | Kakheti and Kazbegi", "Design a Georgia private tour with Tbilisi, Kakheti wine country, Kazbegi mountain views, monasteries, cuisine and private driver-guide support.", "Georgia Wine and Mountains Private Tour"],
  "/private-tour/armenia-monastery-tour": ["Armenia Monastery Private Tour | Yerevan, Sevan and Highlands", "Plan an Armenia monastery private tour with Yerevan, Geghard, Garni, Lake Sevan, highland scenery, local food and flexible day trips.", "Armenia Monastery Private Tour"],
  "/private-tour/azerbaijan-baku-and-gobustan-tour": ["Azerbaijan Baku and Gobustan Private Tour | Caspian Heritage", "Arrange an Azerbaijan private tour with Baku Old City, Gobustan rock art, Absheron fire sites, Caspian views and Caucasus extensions.", "Azerbaijan Baku and Gobustan Private Tour"]
};
for (const [path, [title, description, h1]] of Object.entries(privateTourDetailSeoPages)) {
  staticRouteSeo[path] = { title, description, h1, body: [`${h1} is built for travelers who want a tailored route, transparent logistics and knowledgeable local support rather than a fixed off-the-shelf program.`, "Go To Central Asia can adjust the daily pace, hotel standard, guide language, transport type, border timing, special interests and extensions so the journey fits your dates and travel style."], type: "article" };
}

const extendedAttractionSeoPages = {
  "/attractions/bibi-khanym-mosque": ["Bibi-Khanym Mosque Samarkand | Timurid Landmark Guide", "Visit Bibi-Khanym Mosque in Samarkand with historical context, architecture notes, nearby Siyob Bazaar and tips for Uzbekistan guided tours.", "Bibi-Khanym Mosque Samarkand"],
  "/attractions/siyob-bazaar": ["Siyob Bazaar Samarkand | Food, Bread and Local Market Guide", "Explore Siyob Bazaar in Samarkand for bread, dried fruit, sweets, produce, daily life and a flavorful stop near Bibi-Khanym Mosque.", "Siyob Bazaar Samarkand"],
  "/attractions/ark-fortress": ["Ark Fortress Bukhara | Citadel and Museum Guide", "Discover Ark Fortress in Bukhara with royal history, museum rooms, old city views and practical tips for including it in a Silk Road tour.", "Ark Fortress Bukhara"],
  "/attractions/lyabi-hauz": ["Lyabi Hauz Bukhara | Historic Pool and Old City Guide", "Plan a visit to Lyabi Hauz in Bukhara for madrasahs, tea houses, evening atmosphere, photography and relaxed old city exploration.", "Lyabi Hauz Bukhara"],
  "/attractions/kalyan-minaret": ["Kalyan Minaret Bukhara | Great Minaret Travel Guide", "Learn about Bukhara's Kalyan Minaret, its Silk Road skyline, Poi Kalyan setting, photo angles and guided walking tour context.", "Kalyan Minaret Bukhara"],
  "/attractions/kalta-minor": ["Kalta Minor Khiva | Blue Minaret Attraction Guide", "See Kalta Minor in Khiva's Itchan Kala with tilework details, history, nearby madrasahs and tips for photographing the old city.", "Kalta Minor Khiva"],
  "/attractions/juma-mosque-khiva": ["Juma Mosque Khiva | Wooden Columns and Itchan Kala Guide", "Visit Juma Mosque in Khiva to see carved wooden columns, quiet interior spaces, old city context and Uzbekistan tour planning notes.", "Juma Mosque Khiva"],
  "/attractions/tosh-hovli-palace": ["Tosh Hovli Palace Khiva | Tilework and Royal Courtyards", "Explore Tosh Hovli Palace in Khiva with harem courtyards, blue ceramics, carved wood, royal history and guided sightseeing advice.", "Tosh Hovli Palace Khiva"],
  "/attractions/khast-imam": ["Khast Imam Complex Tashkent | Islamic Heritage Guide", "Visit Khast Imam in Tashkent with mosques, madrasahs, manuscript heritage, old city atmosphere and respectful sightseeing tips.", "Khast Imam Complex Tashkent"],
  "/attractions/tashkent-metro": ["Tashkent Metro Guide | Decorative Stations and City Transit", "Explore the Tashkent Metro's ornate stations, Soviet-era design, practical route tips and how to include it in a city tour.", "Tashkent Metro Guide"],
  "/attractions/amir-timur-square": ["Amir Timur Square Tashkent | City Landmark Guide", "See Amir Timur Square in central Tashkent with nearby museums, hotels, boulevards and context for Uzbekistan capital sightseeing.", "Amir Timur Square Tashkent"],
  "/attractions/charvak-reservoir": ["Charvak Reservoir Uzbekistan | Mountain Lake Day Trip", "Plan a Charvak Reservoir trip from Tashkent with lake views, Chimgan mountains, seasonal activities, private transfers and lunch stops.", "Charvak Reservoir Uzbekistan"],
  "/attractions/chimgan-mountains": ["Chimgan Mountains Uzbekistan | Tashkent Nature Escape", "Visit the Chimgan Mountains near Tashkent for viewpoints, cable car options, fresh air, seasonal snow and easy private day trips.", "Chimgan Mountains Uzbekistan"],
  "/attractions/issyk-kul-lake": ["Issyk-Kul Lake Kyrgyzstan | Beaches, Villages and Mountains", "Explore Issyk-Kul Lake in Kyrgyzstan with lakeside villages, mountain scenery, cultural stops, summer travel tips and private tour planning.", "Issyk-Kul Lake Kyrgyzstan"],
  "/attractions/burana-tower": ["Burana Tower Kyrgyzstan | Silk Road Minaret Guide", "Visit Burana Tower near Bishkek for Silk Road history, balbal stones, mountain views and an easy stop on Kyrgyzstan tours.", "Burana Tower Kyrgyzstan"],
  "/attractions/karakol": ["Karakol Kyrgyzstan | Wooden Mosque, Church and Trails", "Discover Karakol with Dungan Mosque, Orthodox church, food culture, hot springs, trekking gateways and Issyk-Kul route planning.", "Karakol Kyrgyzstan"],
  "/attractions/jety-oguz": ["Jety-Oguz Kyrgyzstan | Red Rocks and Valley Guide", "Visit Jety-Oguz for red sandstone cliffs, the Seven Bulls formation, valley scenery, photo stops and Kyrgyzstan mountain itineraries.", "Jety-Oguz Kyrgyzstan"],
  "/attractions/skazka-canyon": ["Skazka Canyon Kyrgyzstan | Fairytale Rock Formations", "Explore Skazka Canyon near Issyk-Kul with colorful rock shapes, short walks, photography stops and Kyrgyzstan road-trip planning tips.", "Skazka Canyon Kyrgyzstan"],
  "/attractions/charyn-canyon": ["Charyn Canyon Kazakhstan | Valley of Castles Guide", "Plan a Charyn Canyon visit from Almaty with Valley of Castles viewpoints, walking routes, day-trip logistics and Kazakhstan nature tour tips.", "Charyn Canyon Kazakhstan"],
  "/attractions/kolsai-lakes": ["Kolsai Lakes Kazakhstan | Mountain Lake Travel Guide", "Explore Kolsai Lakes in Kazakhstan with forested trails, alpine views, village stays, driving logistics and Almaty nature tour planning.", "Kolsai Lakes Kazakhstan"],
  "/attractions/kaindy-lake": ["Kaindy Lake Kazakhstan | Sunken Forest Guide", "Visit Kaindy Lake in Kazakhstan for its sunken spruce forest, mountain scenery, rough-road access, photo stops and private tour advice.", "Kaindy Lake Kazakhstan"],
  "/attractions/kok-tobe": ["Kok-Tobe Almaty | City Viewpoint and Cable Car Guide", "Add Kok-Tobe to an Almaty city tour for skyline views, cable car access, evening lights, family-friendly stops and Kazakhstan travel context.", "Kok-Tobe Almaty"],
  "/attractions/bayterek-tower": ["Bayterek Tower Astana | Kazakhstan Capital Landmark", "Visit Bayterek Tower in Astana for modern symbolism, city views, nearby architecture and Kazakhstan capital sightseeing ideas.", "Bayterek Tower Astana"],
  "/attractions/iskanderkul-lake": ["Iskanderkul Lake Tajikistan | Fann Mountain Day Trip", "Plan an Iskanderkul Lake trip in Tajikistan with mountain roads, waterfall stops, lakeside views and Fann Mountain itinerary advice.", "Iskanderkul Lake Tajikistan"],
  "/attractions/seven-lakes-tajikistan": ["Seven Lakes Tajikistan | Fann Mountains Route Guide", "Explore the Seven Lakes of Tajikistan with changing water colors, village roads, mountain scenery and private driver logistics.", "Seven Lakes Tajikistan"],
  "/attractions/pamir-highway": ["Pamir Highway Tajikistan | High-Altitude Road Journey", "Plan a Pamir Highway journey with high passes, Wakhan Valley options, village stays, permits, experienced drivers and realistic pacing.", "Pamir Highway Tajikistan"],
  "/attractions/darvaza-gas-crater": ["Darvaza Gas Crater Turkmenistan | Desert Travel Guide", "Visit the Darvaza gas crater in Turkmenistan with Karakum Desert logistics, sunset viewing, camping options and Ashgabat connections.", "Darvaza Gas Crater Turkmenistan"],
  "/attractions/merv": ["Ancient Merv Turkmenistan | UNESCO Silk Road Site", "Explore Ancient Merv in Turkmenistan with UNESCO ruins, caravan history, mausoleums, desert setting and guided Silk Road context.", "Ancient Merv Turkmenistan"],
  "/attractions/nisa": ["Nisa Turkmenistan | Parthian Fortress Travel Guide", "Visit Nisa near Ashgabat to see Parthian archaeological remains, fortress walls, UNESCO heritage and Turkmenistan historical tour notes.", "Nisa Turkmenistan"],
  "/attractions/gobustan": ["Gobustan Azerbaijan | Rock Art and Mud Volcano Guide", "Explore Gobustan near Baku with prehistoric rock art, mud volcanoes, Caspian landscapes and Azerbaijan private tour logistics.", "Gobustan Azerbaijan"],
  "/attractions/baku-old-city": ["Baku Old City Guide | Icherisheher and Caspian Heritage", "Walk Baku Old City with Icherisheher walls, Maiden Tower, Shirvanshah Palace, caravanserais, museums and Azerbaijan tour planning.", "Baku Old City"],
  "/attractions/geghard-monastery": ["Geghard Monastery Armenia | Rock-Cut Sacred Site Guide", "Visit Geghard Monastery in Armenia with rock-cut chapels, mountain scenery, nearby Garni Temple and Yerevan day-trip planning.", "Geghard Monastery Armenia"],
  "/attractions/garni-temple": ["Garni Temple Armenia | Classical Landmark and Gorge Guide", "Explore Garni Temple in Armenia with Hellenistic architecture, Azat Gorge views, lavash experiences and Yerevan excursion tips.", "Garni Temple Armenia"],
  "/attractions/lake-sevan": ["Lake Sevan Armenia | Highland Lake and Monastery Guide", "Plan a Lake Sevan visit in Armenia with Sevanavank Monastery, highland scenery, fish restaurants and private day-trip logistics.", "Lake Sevan Armenia"],
  "/attractions/narikala-fortress": ["Narikala Fortress Tbilisi | Old Town Viewpoint Guide", "Visit Narikala Fortress in Tbilisi for old town panoramas, cable car access, sulfur bath district views and Georgia city tour ideas.", "Narikala Fortress Tbilisi"],
  "/attractions/kakheti-wine-region": ["Kakheti Wine Region Georgia | Vineyards and Villages Guide", "Explore Kakheti wine region with qvevri traditions, vineyards, Sighnaghi, monasteries, tastings and private Georgia route planning.", "Kakheti Wine Region Georgia"],
  "/attractions/kazbegi": ["Kazbegi Georgia | Gergeti Trinity and Mountain Route", "Plan a Kazbegi trip from Tbilisi with Gergeti Trinity Church, Caucasus mountain views, Georgian Military Highway and weather-aware logistics.", "Kazbegi Georgia"]
};
for (const [path, [title, description, h1]] of Object.entries(extendedAttractionSeoPages)) {
  staticRouteSeo[path] = { title, description, h1, body: [`${h1} gives travelers a focused look at one important attraction and how it fits into a wider Central Asia or Caucasus itinerary.`, "Go To Central Asia can combine this stop with nearby sights, private transfers, licensed guides, seasonal timing advice and multi-day tour planning."], type: "article" };
}



const additionalSilkRoadTourSeoPages = {
  "/tour/12-day-uzbekistan-kyrgyzstan-tour": ["12-Day Uzbekistan and Kyrgyzstan Tour | Silk Road and Mountains", "Combine Uzbekistan's Silk Road cities with Kyrgyzstan's alpine lakes, yurt culture, Bishkek, Issyk-Kul and mountain scenery on a 12-day tour.", "12-Day Uzbekistan and Kyrgyzstan Tour"],
  "/tour/14-day-central-asia-tour": ["14-Day Central Asia Tour | Uzbekistan, Kazakhstan and Kyrgyzstan", "Plan a 14-day Central Asia tour linking Uzbekistan monuments, Kazakhstan city-and-canyon highlights and Kyrgyzstan mountain landscapes.", "14-Day Central Asia Tour"],
  "/tour/21-day-five-stans-tour": ["21-Day Five Stans Tour | Complete Central Asia Journey", "Explore all five Central Asian Stans in 21 days with Uzbekistan, Kazakhstan, Kyrgyzstan, Tajikistan, Turkmenistan and coordinated border logistics.", "21-Day Five Stans Tour"],
  "/tour/central-asia-highlights-tour": ["Central Asia Highlights Tour | Silk Road Cities and Mountains", "Book a Central Asia highlights tour with Samarkand, Bukhara, Almaty, Bishkek, mountain scenery, local guides and flexible regional routing.", "Central Asia Highlights Tour"],
  "/tour/uzbekistan-kazakhstan-kyrgyzstan-tour": ["Uzbekistan, Kazakhstan and Kyrgyzstan Tour | 3-Country Route", "Travel Uzbekistan, Kazakhstan and Kyrgyzstan on one guided tour with Silk Road heritage, Almaty nature, Bishkek culture and mountain extensions.", "Uzbekistan, Kazakhstan and Kyrgyzstan Tour"],
  "/tour/tashkent-to-bishkek-tour": ["Tashkent to Bishkek Tour | Uzbekistan and Kyrgyzstan Route", "Plan a Tashkent to Bishkek tour through Uzbekistan's cultural cities and Kyrgyzstan's lake and mountain landscapes with smooth logistics.", "Tashkent to Bishkek Tour"],
  "/tour/almaty-to-tashkent-tour": ["Almaty to Tashkent Tour | Kazakhstan and Uzbekistan", "Connect Almaty and Tashkent with Kazakhstan nature, Uzbekistan city sightseeing, guides, transfers and optional Silk Road extensions.", "Almaty to Tashkent Tour"],
  "/tour/caucasus-three-capitals-tour": ["Caucasus Three Capitals Tour | Tbilisi, Yerevan and Baku", "Visit Tbilisi, Yerevan and Baku on a Caucasus three capitals tour with old towns, monasteries, wine country, Caspian views and private guides.", "Caucasus Three Capitals Tour"],
  "/tour/georgia-armenia-azerbaijan-tour": ["Georgia, Armenia and Azerbaijan Tour | Complete Caucasus Route", "Explore Georgia, Armenia and Azerbaijan in one Caucasus tour with Tbilisi, Yerevan, Baku, mountain roads, monasteries and regional cuisine.", "Georgia, Armenia and Azerbaijan Tour"],
  "/tour/georgia-armenia-tour": ["Georgia and Armenia Tour | Tbilisi, Yerevan and Monasteries", "Combine Georgia and Armenia with Tbilisi, Yerevan, Kakheti wine, Lake Sevan, Garni, Geghard and scenic Caucasus crossings.", "Georgia and Armenia Tour"],
  "/tour/baku-tbilisi-yerevan-tour": ["Baku, Tbilisi and Yerevan Tour | Caucasus Overland Journey", "Travel from Baku to Tbilisi and Yerevan with Caspian heritage, Georgian wine, Armenian monasteries and coordinated cross-border logistics.", "Baku, Tbilisi and Yerevan Tour"]
};
for (const [path, [title, description, h1]] of Object.entries(additionalSilkRoadTourSeoPages)) {
  staticRouteSeo[path] = { title, description, h1, body: [`${h1} gives travelers a ready theme for combining signature places into a practical private or small-group itinerary.`, "Go To Central Asia can refine the route with hotel standards, guide languages, transport choices, border timing, seasonal pacing and pre- or post-tour extensions."], type: "article" };
}

const travelServiceSeoPages = {
  "/private-tour/central-asia-family-tour": ["Central Asia Family Private Tour | Flexible Multi-Country Travel", "Create a Central Asia family private tour with child-friendly pacing, comfortable vehicles, engaging guides, safe hotels and balanced sightseeing days.", "Central Asia Family Private Tour"],
  "/private-tour/central-asia-luxury-tour": ["Central Asia Luxury Private Tour | Premium Silk Road Planning", "Design a luxury Central Asia private tour with premium hotels, expert guides, VIP transfers, refined dining and seamless multi-country logistics.", "Central Asia Luxury Private Tour"],
  "/private-tour/silk-road-honeymoon-tour": ["Silk Road Honeymoon Private Tour | Romantic Uzbekistan and Beyond", "Plan a Silk Road honeymoon tour with boutique hotels, private guides, scenic old cities, relaxed pacing, special dinners and regional extensions.", "Silk Road Honeymoon Private Tour"],
  "/private-tour/central-asia-senior-tour": ["Central Asia Senior Private Tour | Comfortable Guided Itinerary", "Build a senior-friendly Central Asia private tour with gentle pacing, reliable hotels, accessible transport, expert guides and carefully planned sightseeing.", "Central Asia Senior Private Tour"],
  "/private-tour/central-asia-photography-tour": ["Central Asia Photography Private Tour | Silk Road Light and Landscapes", "Plan a Central Asia photography tour around blue-tiled monuments, bazaars, deserts, mountains, golden-hour viewpoints and flexible private logistics.", "Central Asia Photography Private Tour"],
  "/private-tour/central-asia-culinary-tour": ["Central Asia Culinary Private Tour | Markets, Plov and Home Meals", "Taste Central Asia on a culinary private tour with bazaars, plov, bread, tea traditions, home meals, cooking experiences and cultural sightseeing.", "Central Asia Culinary Private Tour"]
};
for (const [path, [title, description, h1]] of Object.entries(travelServiceSeoPages)) {
  staticRouteSeo[path] = { title, description, h1, body: [`${h1} focuses on travel style as much as destination choice, making the itinerary easier to match to real expectations.`, "Our planners can adjust hotel comfort, walking intensity, meal experiences, guiding depth, rest time and route complexity before confirming the final program."], type: "article" };
}

const practicalAttractionSeoPages = {
  "/attractions/margilan-silk-factory": ["Margilan Silk Factory | Ferghana Valley Craft Guide", "Visit Margilan silk workshops in the Ferghana Valley to see ikat weaving, cocoon processing, artisan traditions and Uzbekistan craft tour ideas.", "Margilan Silk Factory"],
  "/attractions/rishtan-ceramics": ["Rishtan Ceramics Guide | Ferghana Valley Artisan Workshops", "Explore Rishtan ceramics with blue pottery workshops, master artisans, local studios and Ferghana Valley private tour planning tips.", "Rishtan Ceramics"],
  "/attractions/kokand-palace": ["Kokand Palace Guide | Khudayar Khan and Ferghana Heritage", "Visit Kokand's Khudayar Khan Palace with tiled courtyards, museum rooms, khanate history and Ferghana Valley itinerary context.", "Kokand Palace"],
  "/attractions/ulugbek-observatory": ["Ulugbek Observatory Samarkand | Astronomy Heritage Guide", "Discover Ulugbek Observatory in Samarkand with medieval astronomy history, museum context and how it complements Registan sightseeing.", "Ulugbek Observatory Samarkand"]
};
for (const [path, [title, description, h1]] of Object.entries(practicalAttractionSeoPages)) {
  staticRouteSeo[path] = { title, description, h1, body: [`${h1} adds depth beyond headline monuments by connecting travelers with science, craft, regional history or living traditions.`, "This stop can be combined with nearby sightseeing, private transfers, specialist guide explanations and route timing planned by Go To Central Asia."], type: "article" };
}

export const staticPrerenderPages = Object.entries(staticRouteSeo).map(([path, page]) => ({ path, ...page }));
